clibs/clib

- src/clib-install.c
Use gzip -dc. "tar xf" dosn't extract "tar.gz". "tar xzf" can do it. But it doesn't work on windows
> Doesn't extract tar.gz

- Makefile
- test.sh
cygwin do not use 
```
LDFLAGS = -lcurldll
CP      = copy /Y
RM      = del /Q /S
MKDIR_P = mkdir
```
and do not use
```
BINS    = clib clib-install clib-search
```
but use 
```
BINS    = clib.exe clib-install.exe clib-search.exe
LDFLAGS = -lcurl
CP      = cp -f
RM      = rm -f
MKDIR_P = mkdir -p
```
and i use `ifeq ($(shell uname -o),Cygwin)` to identify it.
> Add cygwin compatible

- deps/list/list.c
- deps/list/package.json
- deps/occurrences/occurrences.c
- deps/occurrences/occurrences.h
- deps/occurrences/package.json
- deps/parson/package.json
- deps/parson/parson.c
- deps/parson/parson.h
- deps/str-concat/package.json
- deps/str-concat/str-concat.c
- deps/str-concat/str-concat.h
- deps/str-copy/package.json
- deps/str-copy/str-copy.c
- deps/str-copy/str-copy.h
- deps/str-ends-with/package.json
- deps/str-ends-with/str-ends-with.c
- deps/str-ends-with/str-ends-with.h
- deps/str-replace/package.json
- deps/str-replace/str-replace.c
- deps/str-replace/str-replace.h
- package.json
- src/clib-install.c
- test/data/test-save-package.json
- test/install-save.sh
Hey Team;
I've added the --save and --save-dev options to clib-install. I needed to update the dependencies with the latest version of parson to support pretty JSON writing. The gist of the update is in `src/clib-install.c`. My C is a little rusty, so feel free to throw any feedback my way.
Thanks!
Chris
Fixes #19
Fixes #20
> Add --save and --save-dev Options to clib-install

- Makefile
I needed this change to get clib to compile under FreeBSD, where I had installed libcurl via pkgng. I'm not sure as I haven't tested on other platforms yet but apparently this was added in curl 7.7.2 (http://curl.haxx.se/libcurl/using/) and should be available with most libcurl installations.
Perhaps there's a better way to do this if it is desired to support older versions of libcurl?
> Add 'curl-config' to Makefile to find cURL

- scripts/ccan2clib.py
- scripts/convert_all_ccan2clib.sh
This script converted the ccan ```build_assert``` module into the ```clibs/build_assert``` mirror repo. But yet, I still had to manually create the repo in Github and ```git commit -am ‘Initial commit’; git push```.
This approach of mirroring ccan modules is good thanks to the ```repo``` package.json key. This means clib will always download the latest source files from ```rustyrussell/ccan```.
I want to create repo mirrors for all of ccan, but before that I wonder:
* is it a good idea to put all the ccan mirror modules into their own organisation, eg. ```ccan-clibs/*```? Otherwise, we should put all the ccan mirror repos into ```clibs/*```
*  is there a way to automatically create Github repos (maybe via the HTTP API)?
> Add ccan to clib conversion script

- .travis.yml
- Makefile
- test.sh
It only took 32 tries, but I'm confident it'll build now! This PR is to open discussion about using [GitHub Releases Uploading](https://docs.travis-ci.com/user/deployment/releases/) to attach pre-compiled Windows binaries to future Github releases. I've got the compiling bit done. Specifically, a statically linked `clib` with libcurl.
Travis Build: https://travis-ci.org/wmhilton-contrib/clib/builds
> Pre-compiled Windows binaries for future Github releases

- .travis.yml
This is a followup to #143 that adds the Travis config to upload the compiled binaries back to Github. I've tested it on [my fork](https://github.com/wmhilton-contrib/clib/releases) and the only change that needs to be made is to swap the encrypted OAuth token that has `public_repo` access to *my* repository with one that has `public_repo` access to *this* repository. Either by using travis' encryption or by making a token in Github's settings and adding it to the Environment Variables settings in Travis.
> Upload Windows binaries to tagged Github Releases

- Readme.md
- scripts/convert_all_ccan2clib.sh
- test.sh
- test/gh-35-exit-codes.sh
- test/help.sh
- test/install-binary-dependencies.sh
- test/install-brace-expansion.sh
- test/install-deps-from-package-json.sh
- test/install-multiple-clibs-libs.sh
- test/install-multiple-libs.sh
- test/install-save.sh
- test/search-basic.sh
- test/search-no-color.sh
No functional changes. The goal of this patch is to remove the
dependency on bash and instead be compatible to POSIX sh, to be
installed on prisitine Unix like systems (*BSD, minix, alpineLinux, etc).
[shellcheck](http://shellcheck.net) was used to lint shell scripts.
- Use `#!/bin/sh` in place of `#!/bin/bash`
- fix non portable shell syntax
- slight syntax improvements as reported by `shellcheck -s sh` linter
> Portability: make shell scripts POSIX sh compatible

- Readme.md
- src/clib.c
Mention init command in clib's help.
> fixed: mention init in clib's help.

- src/clib-install.c
- src/clib-search.c
This PR finally integrates `clib-cache` into `clib` intself. 
I opened PR #146 a long time ago, but never finished and became outdated. Since `clib` already uses the newest `clib-package` which has the cache already integrated, we only need to initialize the cache in the executable. 
The main feature it adds is package caching for each version of them, giving a huge performance boost. The `clib-search` cache is also moved there. 
If you guys could give it some extra test, that would be awesome, especially on Windows.
@clibs/core
> Integrating clib-cache

- src/clib-search.c
This is the implementation of #166 
`clib search` with `--json` flag will generate a JSON searialzed output, so other tools can build upon it easily.
> Add --json flag to clib search

- src/clib-install.c
Just to avoid confusion between packages and "manifest" files.
> fixed: rename package_names to manifest_names.

- Makefile
Hi, I've fixed 45 missing dependencies reported.
Those issues can cause incorrect results when clib is incrementally built.
For example, any changes in "deps/list/list.h" will not cause "deps/list/list.o" to be rebuilt, which is incorrect.
I've tested it on my computer, the fixed version worked as expected.
Looking forward to your confirmation.
This is a follow-up PR of PR https://github.com/clibs/clib/pull/167. 
This PR fixes all the dependency issues reported in  [report.txt](https://github.com/clibs/clib/files/3493047/report.txt). 
@lsty
> Makefile: fix 45 missing prerequisites reported by Vemake

- src/clib-install.c
Initializes curl globally in main function. This will let any functions use the curl API to use them safely. The PR also cleans up call at the end of the main function
> refactor(src/clib-install.c): init and cleanup curl

- Readme.md
- src/clib.c
This PR address a bug in the parsing of the capital `-V` switch when checking the currently installed version.
> fix(): capital -V version switch

- BEST_PRACTICE.md
> fix(BEST_PRACTICES.md): fix typo in best practice doc

- Makefile
- Readme.md
- scripts/pre-commit-hook.sh
- src/clib-build.c
- src/clib-configure.c
- src/clib-init.c
- src/clib-install.c
- src/clib-search.c
- src/clib-update.c
- src/clib-upgrade.c
- src/clib.c
- src/common/clib-cache.c
- src/common/clib-cache.h
- src/common/clib-package.c
- src/common/clib-package.h
This patch introduces `clang-format` to ensure our source files have consistent "code style".
Two new Make targets have been created:
- `make fmt`: run `clang-format` on all source files (in the `src/` directory)
- `make commit-hook`: install a `pre-commit` hook for automatically running `clang-format` on changes
Closes #208
> Add `clang-format` for code formatting

- src/clib-upgrade.c
- This PR adds a warning for a future change in `clib upgrade` (#212). In the log I marked 2.6.0 for the change, so 3 releases from now, I think it's a reasonable time for that, but please let me know what you think about that.
- Fixes a bug where the `--tag` option was ignored.
- Adds an error log when a tag cannot be installed.
I hope it's okay that I coupled a few small things to this PR. :smile:
> Logging future change in clib upgrade

- deps/http-get/clib.json
- deps/http-get/http-get.c
- deps/http-get/http-get.h
- src/clib.c
- src/common/clib-cache.c
- src/common/clib-cache.h
- src/common/clib-package.c
The PR is the implementation of #213
> Notifying the user if new version is available 

- BEST_PRACTICE.md
There is a small typo in BEST_PRACTICE.md.
Should read `release` rather than `relese`.
> docs: fix simple typo, relese -> release

- Readme.md
Looks like [ashworth.in](http://blog.ashworth.in/2014/10/19/the-advent-of-clib-the-c-package-manager.html) is gone. Replaced that link with [archive.org ](https://web.archive.org/web/20200128184218/http://blog.ashworth.in/2014/10/19/the-advent-of-clib-the-c-package-manager.html) link.
> doc(README.md): Replace dead link with archive.org's

- test/fuzzing/fuzz_manifest.c
This PR adds a fuzzer that targets clib_package_load_from_manifest.
The fuzzer can be run locally and I can confirm that it runs on oss-fuzz's infrastructure as well. I will be happy to setup an integration application into oss-fuzz if the maintainers of Clib are interested in running this fuzzer continuously and in fixing bugs if any should be found.
Integration into oss-fuzz is free, but bugs need to be fixed so that the resources spent on fuzzing Clib are put to good use. Oss-fuzz has a 90 day disclosure policy.
> Add fuzzer

- Readme.md
- src/clib.c
This small change removes the long time deprecated `-v` flag in favor of  `-V`, also adds small notice about GitHub Discussion in the Readme.md.
> Removing deprecated -v flag

- src/clib-search.c
Frees all pointers from strdup.
Before:
```
$ clib-search foo
[...]
Process 71040: 1070 nodes malloced for 55 KB
Process 71040: 562 leaks for 19648 total leaked bytes.
562 (19.2K) << TOTAL >>
```
Yup, almost a whopping 20Kbs of leaked memory.
After:
```
$ clib-search foo
[...]
Process 71043: 508 nodes malloced for 36 KB
Process 71043: 0 leaks for 0 total leaked bytes.
```
And now, there is no leaks!
> Fixed memory leak for clib-search

- src/clib-configure.c
Frees the json pointer if it was allocated before attempting to modify it.
Before:
```
$ valgrind --tool=memcheck --leak-check=yes clib-configure
[...]
LEAK SUMMARY:
definitely lost: 1,268 bytes in 2 blocks
indirectly lost: 0 bytes in 0 blocks
possibly lost: 0 bytes in 0 blocks
still reachable: 3,108 bytes in 163 blocks
suppressed: 0 bytes in 0 blocks
```
Just from running this command, we lost over 1.2k of memory. Thats about 0.00023% of the raspberry pi zero's ram (512Mbs). Lol :)
After:
```
$ valgrind --tool=memcheck --leak-check=yes ~/github-repo/westleyr-clib/clib/clib-configure
[...]
definitely lost: 9 bytes in 1 blocks
indirectly lost: 0 bytes in 0 blocks
possibly lost: 0 bytes in 0 blocks
still reachable: 3,108 bytes in 163 blocks
suppressed: 0 bytes in 0 blocks
```
As you can …
> Fix memory leak

- src/common/clib-cache.c
- test/cache/cache-test.c
The search HTML cache was never expired. Fixed it to use the expiration time set by `clib_cache_init`.
> Expire the search cache

- src/clib-upgrade.c
- src/clib.c
- src/common/clib-package.c
- src/common/clib-package.h
Fixing compiler warnings when executing `make`
> Fixing compiler warnings

- src/common/clib-package.c
Fixing a warning thrown by clang as seen [here](https://github.com/clibs/clib/runs/1686786074?check_suite_focus=true#step:4:114).
> Warnings generated by clang

- src/clib-init.c
> clib init can't always determine the current directory name

- src/clib.c
In relation to #190 this feature will be removed, even if not really used, I think it's a bit cleaner to deprecate it first, then eventually remove it. Marked it as to be removed in 3.0 because IMO a change like #190 'deserves' a major version.
> deprecating clib-* plugins

- .gitignore
- Makefile
- deps/http-get/clib.json
- deps/http-get/http-get.h
- src/clib-uninstall.c
- src/clib.c
- test/uninstall.sh
Moving clibs/clib-uninstall into clib.
> Intergrating clib-uninstall

- src/clib-build.c
- src/clib-configure.c
- src/clib-init.c
- src/clib-install.c
- src/clib-search.c
- src/clib-uninstall.c
- src/clib-update.c
- src/clib-upgrade.c
- src/common/clib-package.c
On cygwin, `setenv` and `realpath` are implemented
(`_putenv_s` and `_fullpath` are not implemented.)
```
src/common/clib-package.c: In function ‘set_prefix’:
src/common/clib-package.c:53:24: warning: implicit declaration of function ‘_fullpath’ [-Wimplicit-function-declaration]
53 | #define realpath(a, b) _fullpath(a, b, strlen(a))
|                        ^~~~~~~~~
src/common/clib-package.c:1077:7: note: in expansion of macro ‘realpath’
1077 |       realpath(opts.prefix, path);
|       ^~~~~~~~
src/common/clib-package.c:52:25: warning: implicit declaration of function ‘_putenv_s’; did you mean ‘_putenv_r’? [-Wimplicit-function-declaration]
52 | #define setenv(k, v, _) _putenv_s(k, v)
|                         ^~~~~~~~~
src/common/clib-package.c:1083:5: note: in expansion of macro …
```
> Fix compile error on cygwin

- src/common/clib-package.c
There is a bug in the multithreading code when downloading package files. I have added some debug statements to highlight the problem.
Without fix:
```
$ clib-install -c -f thlorenz/gumbo-parser.c
warning : missing repo in clib.json or package.json file for (null)
fetch : thlorenz/gumbo-parser.c:package.json
warning : missing repo in clib.json or package.json file for gumbo-parser
Starting thread 0
fetch : thlorenz/gumbo-parser:src/attribute.c
Starting thread 1
fetch : thlorenz/gumbo-parser:src/attribute.h
Starting thread 2
fetch : thlorenz/gumbo-parser:src/char_ref.c
Starting thread 3
fetch : thlorenz/gumbo-parser:src/char_ref.h
Starting thread 4
fetch : thlorenz/gumbo-parser:src/error.c
All threads in use, cleaning up.
save : ./deps/gumbo-parser/attribute.c
save : …
```
> Fix a memory issue when downloading files.

- BEST_PRACTICE.md
- src/clib-build.c
- src/clib-configure.c
- src/clib-install.c
- src/clib-search.c
- src/clib-uninstall.c
- src/clib-update.c
- src/clib-upgrade.c
- src/common/clib-package.c
- src/common/clib-settings.h
I think that it is more clear to define the thread count, cache time and manifest names in one place.
> Enhancement: Move common settings to a settings header and use clib.json instead of package.json in BEST PRACTICES

- src/clib-build.c
- src/common/clib-settings.c
- src/common/clib-settings.h
- test/package/Makefile
I forgot to make the manifest names static. Therefore the variable was exposed by every unit that included the compile_settings, which caused the multiple definition errors when linking.
> bugfix for compile_settings

- .github/workflows/release.yml
- .github/workflows/tests.yml
- .gitignore
- Makefile
- scripts/feature-test-pthreads
I think that it should be possible to make the windows builds multi threaded as well.
> Implement building multithreaded for windows.

- test/package/package-install-dependencies.c
- test/package/package-install-dev-dependencies.c
- test/package/package-install.c
Looks like a possible source of these random failings, and wild seg faults is that the cache is not initialized in some tests where it's actually used. For some reason it causes some completely unrelated issues in the mac build. Probably the uninitialized variables corrupted the memory.
> Fixing the failing tests on MacOS

- src/common/clib-package.c
Probably (:crossed_fingers:) this is root cause of the randomly failing mac tests.  
According to `man 3 basename` `These functions may return pointers to statically allocated memory which may be overwritten by subsequent  calls.`, and as it can be seen in the messy logs in #272 I've added there it's true on that environment, since the parallel threads keep overriding the same address. Then `path_join` allocates N bytes but when it tries to concat the two strings the value of `file` is changed to something larger thus causing an overflow. 
As I can see this is the only place where `basename` is used concurrently and might cause this error, but let me know if there are other problematic usages. 
ASAN output:
```
1 warning generated.
(✓) test/install-binary-dependencies.sh
(✓) …
```
> Heap buffer overflow reported by Address Sanitizer

- Makefile
- src/clib-build.c
- src/clib-install.c
- src/clib-update.c
The `PREFIX` environment variable was not set properly from various `clib` commands. This pull request fixes it.
> Fix install prefix

- src/clib-install.c
- src/clib-update.c
In the changed code, `name` is assigned a pointer, that was some offset value from `manifest_names`.
`manifest_names` is defined like so:
```c
extern const char *manifest_names[];
```
In all cases, `name` is being passed into the `fs_read` function, which has the following declaration:
```c
char *fs_read (const char *path);
```
Because the "source" and "destination" of `name` has a type of `const char *`, changing `name` to match that improves consistensy. This also fixes a `-Wdiscarded-qualifiers` warning that may show upon compilation.
> fix: Do not discard `const` type qualifier

- Makefile
- src/clib-install.c
- test/install-binary-dependencies.sh
- test/install-brace-expansion.sh
- test/install-multiple-clibs-libs.sh
- test/install-multiple-libs.sh
- test/install-no-save.sh
- test/install-save.sh
- test/uninstall.sh
This PR modifies the behavior of `clib-install` such that dependencies are saved to the clib manifest (clib.json/package.json) by default, mirroring the behavior of npm >= 5. It accomplishes this by deprecating the `--save` option and adding an additional flag `--no-save` which can be passed to prevent the dependency from being written to the clib manifest. 
Note I've retained the `--save-dev` option so users can specify they want the dependency to save under dev dependencies. This is also aligned with the behavior of npm >= 5. 
Changes:
- Deprecate `--save` option and add a logger warning. Behavior when this flag is passed is effectively the same to prevent backward compatibility issues.
- Add new `--no-save` flag, which changes the install behavior such that the dependency is not added …
> #291: Save dependencies to clib manifest by default

- .github/workflows/release.yml
- .github/workflows/tests.yml
A low-hanging fruit fix that addresses [some](https://github.com/clibs/clib/actions/runs/6804237760) of the `set-output` and `node12` deprecation errors.
More investigation may be needed to replace deprecated or unmaintained actions, such as `little-core-labs/get-git-tag@v3.0.1`, `actions/create-release@v1`, and `actions/download-artifact@v1`.
> ci: Upgrade actions

- Makefile
As noted in the issue, when files like `src/common/clib-cache.c` were modified, running `make` did not rebuild `clib`. Now, it does.
Closes #298
Closes #284
Closes #276
> fix(makefile): Add missing dependencies from `src/common/*`

- Makefile
- scripts/feature-test-pthreads
Some platforms (android, really) do not implement `pthread_cancel` and a few other functions, so this PR
adds a check for such cases.
Besides that, `HAVE_PTHREADS` must not be defined at all when pthread is not available.
Related: #304
> Additional check for pthread_cancel

- test/fuzzing/fuzz_manifest.c
To fix a clang-18 error:
```
test/fuzzing/fuzz_manifest.c:25:5: error: call to undeclared function 'unlink'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
25 |     unlink(filename);
|     ^
1 error generated.
ERROR:__main__:Building fuzzers failed.
> Update fuzz_manifest.c: Add missing include unistd.h

- test.sh
- test/install-binary-dependencies.sh
- test/install-brace-expansion.sh
- test/install-deps-from-package-json.sh
- test/install-multiple-clibs-libs.sh
- test/install-multiple-libs.sh
- test/install-no-save.sh
- test/install-save.sh
- test/uninstall.sh
This PR fixes some of the issues in [this ci failure](https://github.com/clibs/clib/actions/runs/6804237760/job/18501316937#step:6:1507) and false negatives when running tests locally (e.g. due to inadvertently running the cache tests twice). 
Changes:
- Use traps to cleanup test artifacts (in case a test fails, we don't leave the artifacts to potentially cause false negatives in the next test).
- Allow ctrl+c to fast-exit from test script 
- Ensure all binary installs in tests set the prefix opt (avoids perms issues in some systems)
- Fix test script such that cache tests only run once
Thanks 
@jwerle @stephenmathieson
> Fix failing tests, cleanup issues w/running tests locally

- Readme.md
**It really took me a long time to find out how to install `libcurl`** when I was trying to install Clib on Fedora Linux.
How about adding the installation instruction for Fedora to `Readme.md`?
> Add installation instruction for Fedora

- src/common/clib-package.c
The leak was found by fuzzer:
```
=================================================================
==335809==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 32 byte(s) in 1 object(s) allocated from:
#0 0x55f752b5da5e in malloc (clib/myfuzzing/prefix/bin/fuzz_manifest+0x117a5e)
#1 0x55f752bbfa4a in json_object_init clib/deps/parson/parson.c:291:42
#2 0x55f752bbf8e9 in json_value_init_object clib/deps/parson/parson.c:1077:31
#3 0x55f752bc839f in parse_object_value clib/deps/parson/parson.c:580:32
#4 0x55f752bbd0e4 in parse_value clib/deps/parson/parson.c:561:20
#5 0x55f752bc8a6e in parse_object_value clib/deps/parson/parson.c:600:21
#6 0x55f752bbd0e4 in parse_value clib/deps/parson/parson.c:561:20
#7 0x55f752bbc55a in json_parse_string clib/deps/parson/parson.c:910:12
#8 …
```
> Fix memory leak in clib_package_new

- src/clib-uninstall.c
The execution of ```return``` on line 131  leads to memory leaks because cleanup code at the end of the function is not called in this case.
Therefore, I removed ```return``` to avoid memory leaks.
> Fix possible memory leak

- src/clib-install.c
the names was used when writing the dependencies which causes this
$ clib install package@0.1.0
is written on json as
"package@0.1.0": "0.1.0"
Closes #330
> fix(clib-install): check if version was specified when installing.
